"""initializing new table book

Revision ID: 9f1950c6c6a4
Revises: 
Create Date: 2023-06-28 14:32:55.040920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1950c6c6a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('releaseDate', sa.Text(), nullable=False),
    sa.Column('isbn', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
